### ISSUE TITLE
CreateTempDirPath is not called

### ISSUE THREAD

**Issue by jclinn** [jfrog/jfrog-client-go#1]
I tried following the examples in the README to download an artifact but kept getting the following error:

[Error] [Thread 2]  Received an error: Function cannot be used before 'tempDirPath' is created.

I had to call fileutils.CreateTempDirPath() before the download works.

Please update the documentation or update the flow to call fileutils.CreateTempDirPath() within DownloadFiles.

The documentation is limited so would be best if you create an end to end example/test using 
ArtifactoryServicesManager.

**Comment by eyalbe4** [comment]
Thanks @jclinn,
We are currently working on updating the jfrog-client library. It is still new and requires some improvements and tunings. It has only recently been separated from the jfrog-cli project, which will soon be updated to use it as a dependency.

**Comment by jclinn** [comment]
Do you recommend using this go client or should I hit the Artifactory api directly?

**Comment by eyalbe4** [comment]
@jclinn,
During the next couple of weeks we intend make a lot of changes to the go-client, which include API changes and bug fixes. Once done, we'd love people to use it and contribute to it. You can perhaps start by using the REST APIs directly and then, if possible migrate to the go-client.

**Comment by eyalbe4** [comment]
@jclinn -
I think that following the recent changes and improvements to the client, specifically on the latest release, this issue can be closed.
Feel free ti share with us your feedback.
