### ISSUE TITLE
Create Token without expiry (ExpiresIn=0) not possible (token is issued with default expiry)

### ISSUE THREAD

**Issue by markuslackner** [jfrog/jfrog-client-go#127]
Currently its not possible to create a token without expiry over the api. The reason is this code:

https://github.com/jfrog/jfrog-client-go/blob/74b10e4efa5cfc819f061cbf3bbba99d6f7cb6b6/artifactory/services/security.go#L139

=> If you specify "0" the expires_in is not send to the server and the default is used.

**Comment by eyalbe4** [comment]
Thanks for reporting this @markuslackner.
Feel free to create a pull request to change this behaviour.
