### ISSUE TITLE
Support POST maven_central_sync

### ISSUE THREAD

**Issue by bootstraponline** [jfrog/jfrog-client-go#148]
It'd be great to support the `POST maven_central_sync` endpoint.

```kotlin
POST /maven_central_sync/:subject/:repo/:package/versions/:version
{
  "username": "userToken", // Sonatype OSS user token
  "password": "passwordToken", // Sonatype OSS user password
  "close": "1" // Optional
}
```
https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central

**Comment by kowalczykp** [comment]
I'd be happy to pick this up @eyalbe4 @bootstraponline 

I've raised https://github.com/jfrog/jfrog-client-go/pull/154 to address the addition of this request

**Comment by eyalbe4** [comment]
Thank you for this @kowalczykp!
