### ISSUE TITLE
No longer able to compile

### ISSUE THREAD

**Issue by rpetti** [jfrog/jfrog-client-go#17]
Hi,
It seems that this package is no longer usable. It it still being maintained?

When I try to compile anything using it, I get
```
../../github.com/jfrog/jfrog-client-go/httpclient/client.go:252:10: undefined: archiver.MatchingFormat
../../github.com/jfrog/jfrog-client-go/httpclient/client.go:306:12: arch.Read undefined (type archiver.Archiver has no field or method Read)
../../github.com/jfrog/jfrog-client-go/httpclient/client.go:316:20: invalid method expression archiver.Zip.Open (needs pointer receiver: (*archiver.Zip).Open)
../../github.com/jfrog/jfrog-client-go/httpclient/client.go:316:20: archiver.Zip.Open undefined (type archiver.Zip has no method Open)
../../github.com/jfrog/jfrog-client-go/httpclient/client.go:476:10: undefined: archiver.MatchingFormat
```

This appears to be caused by one of the dependencies (https://github.com/mholt/archiver) having been recently rewritten.

**Comment by eyalbe4** [comment]
@rpetti,
We'll soon add instructions to the README describing how to use this module.
It has been recently converted to use *go-modules* as a package manager, so it should be built a bit differently than the way legacy go projects used to be built.
The *jfrog-client-go* is still in its beta phase and therefore goes through massive API changes, but we're happy to see it is being used by other projects already.
We'll update this issue once we add the instructions.

**Comment by rpetti** [comment]
Thanks for the update. Can you also consider adding a disclaimer stating that this module is beta and not ready for production? One of our production services is now un-buildable due to this issue.

**Comment by eyalbe4** [comment]
@rpetti,
The README has been updated. 
Please let us know if you have additional questions or suggestions.
