### ISSUE TITLE
--interactive=false not working

### ISSUE THREAD

**Issue by cdancy** [jfrog/jfrog-client-go#26]
Using the latest and greatest it's telling me that `--interactive` is telling me that the flag is provided but not defined?
```
./jfrog rt ping --interactive=false --user=admin --password=admin --url=http://some-artifactory-instance
```
Any thoughts?

**Comment by cdancy** [comment]
I need the interactive=false flag as this is being run in a CI environment.

**Comment by cdancy** [comment]
Furthermore I need it to publish a helm chart unless of course you guys provide an easier way.

**Comment by yahavi** [comment]
@cdancy, 
The `interactive` flag purpose is to determine whether we want the server configuration (`jfrog rt c`) to be interactive or not. on the other hand, `JFROG_CLI_OFFER_CONFIG` environment variable determine in all commands if we want to configure Artifactory server in case it doesn't exist. 

Please use the following command:
`JFROG_CLI_OFFER_CONFIG=false ./jfrog rt ping --user=admin --password=admin --url=http://some-artifactory-instance`

or

```
export JFROG_CLI_OFFER_CONFIG=false
./jfrog rt ping --user=admin --password=admin --url=http://some-artifactory-instance
```

For more information: 
https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-EnvironmentVariables

**Comment by cdancy** [comment]
Really? We have to export an env-var just to use it without being prompted? Seems weird but OK. Thanks.
