### ISSUE TITLE
Is there a way to set Destination when creating a permission 

### ISSUE THREAD

**Issue by sguiheux** [jfrog/jfrog-client-go#315]
Hello,

In artifactory UI, when creating a permission there is a Destination section.
I don"t found in the go client where i can manipulate this data (create/update/delete).

The structure PermissionTargetParams do not contains the Destination section
```
// Using struct pointers to keep the fields null if they are empty.
// Artifactory evaluates inner struct typed fields if they are not null, which can lead to failures in the request.
type PermissionTargetParams struct {
	Name          string                   `json:"name"`
	Repo          *PermissionTargetSection `json:"repo,omitempty"`
	Build         *PermissionTargetSection `json:"build,omitempty"`
	ReleaseBundle *PermissionTargetSection `json:"releaseBundle,omitempty"`
}
```

There is another way to do this? or it's just missing for now and will be added in the future ?

**Comment by yahavi** [comment]
@sguiheux,
To create/update a permission target, we use the following API: [/api/v2/security/permissions/{permissionTargetName}](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API+V2#ArtifactoryRESTAPIV2-CreatePermissionTarget). 
This API consumes [PermissionTargetV2](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json) JSON and supported on Artifactory 6.6 and above. What is your Artifactory version?

I'm not sure - what is the destination field?
Can you please provide a screenshot of the relevant section of your Artifactory UI?

Thanks.
