### ISSUE TITLE
Please Consider Semantic Versioning

### ISSUE THREAD

**Issue by zbindenren** [jfrog/jfrog-client-go#34]
Please consider [semantic versioning](https://semver.org/).

You tagged a new release 0.2.2 18h ago, but this version is incompatible with 0.2.1. Patch releases should be backwards-compatible bug fixes.

**Comment by RobiNino** [comment]
@zbindenren,
You are correct. Following the API changes, this should have been released as a minor release and not a patch. We apologise for the inconvenience caused by this.
We've just updated the README with the API changes and released a new minor version.
Thanks
