### ISSUE TITLE
return sha256 as a field when running rt s

### ISSUE THREAD

**Issue by lorenyeung** [jfrog/jfrog-client-go#436]
Looking for sha256 as a return field when searching for something on Artifactory via the cli (edited response for brevity):

```
$ jfrog rt s ' npm/pkg/-/pkg-1.0.0.tgz'
[Info] Searching artifacts...
[Info] Found 1 artifact.
[
  {
    "path": "npmjs-cache/pkg/-/pkg-1.0.0.tgz",
    "type": "file",
    "size": 5603,
    "created": "2021-02-20T21:10:48.531Z",
    "modified": "2015-05-22T14:10:50.000Z",
    "sha1": "831ae9s2d7508c50401e3e06fsfe1e8c574eabcs",
    "md5": "21268f11fda543511416fdab2c60abgw",
    "props": {
      "npm.version": [
        "1.0.0"
      ]
    }
  }
]
```

**Comment by eyalbe4** [comment]
@lorenyeung - 
Thanks for submitting this request. Since however this request is for jfrog-cli, I suggest you open it under https://github.com/jfrog/jfrog-cli and kindly close this one.

**Comment by FelixZoox** [comment]
Created a copy of [this ](https://github.com/jfrog/jfrog-cli/issues/1237#issue-1010242213) in jfrog-cli, so this can likely be closed.
