### ISSUE TITLE
For ease of testing, Properties struct should encode values in predictable/sorted order.

### ISSUE THREAD

**Issue by AnalogJ** [jfrog/jfrog-client-go#549]
**Is your feature request related to a problem? Please describe.**
Our test framework uses Go-VCR which allows us to run our integration test suite without interacting with a real Artifactory server. We've noticed that our tests will occassionally fail because a "recording" could not be found. This is because the generated URL can be different between runs:

```
https://artifactory.corp.example.com/artifactory/myrepository/test/archive.tar.gz;upload_path=test%2Farchive.tar.gz;repo_org=git;repo_name=test":

https://artifactory.corp.example.com/artifactory/myrepository/test/archive.tar.gz;repo_name=test;repo_org=git;upload_path=test%2Farchive.tar.gz"
```

**Describe the solution you'd like to see**
The `ToEncodedString()` function should always generate a string in a predictable/sorted order.
https://github.com/jfrog/jfrog-client-go/blob/e3c6206b724288677c125d89268f461a78c33e57/artifactory/services/utils/properties.go#L97

**Comment by SteveNewson** [comment]
@yahavi This can now be closed.
