### ISSUE TITLE
Support for Access Tokens API

### ISSUE THREAD

**Issue by jsok** [jfrog/jfrog-client-go#55]
Are there plans to add support for the various access token capabilities via the REST API?

As documented here: https://www.jfrog.com/confluence/display/ACC/Access+Tokens#AccessTokens-RESTAPI

**Comment by eyalbe4** [comment]
@jsok,
Currently the client supports using Access Tokens for authentication.
Are you asking about support for token creation? Can you elaborate more the need and your use case?

**Comment by jsok** [comment]
Yes token creation (and revoke etc) are the APIs I'm interested in.

I'm writing a plugin for [Vault](https://github.com/hashicorp/vault) to dynamically issue access tokens. Using an official go library for the integration is generally preferred over a bespoke implementation.

Although in this case it's only 2 or 3 API endpoints to implement so if it's not something on your radar I'm decided if I should just implement it in the plugin, or create a PR to add the support myself.

**Comment by jsok** [comment]
Looks like #85 has implemented this functionality

**Comment by eyalbe4** [comment]
Correct @jsok.
The functionality has already been released. See the README for usage information. 
Feel free to close this issue.
