### ISSUE TITLE
GetAllRepositoriesFiltered(params services.RepositoriesFilterParams) should honor the API

### ISSUE THREAD

**Issue by Raghed22** [jfrog/jfrog-client-go#812]
We are able to search for all Repositories in the project through the API but not using the client

Consider handling the project parameter here:
type RepositoriesFilterParams struct {
	RepoType    string
	PackageType string
}
[The code](https://github.com/jfrog/jfrog-client-go/blob/master/artifactory/services/repositories.go#L113) needs to reflect the API:
https://jfrog.com/help/r/jfrog-rest-apis/get-repositories

Br,
Raghed Ali

**Comment by eyalbe4** [comment]
Thanks for raising this @Raghed22.
We'd welcome a pull request that adds this.

**Comment by Or-Geva** [comment]
Hey @Raghed22, I have just opened a [PR](https://github.com/jfrog/jfrog-client-go/pull/1007) that addresses your needs. I will update you on this thread once it is released.

**Comment by yahavi** [comment]
@Raghed22  
JFrog Go client version 1.46.0 has been released, now with support for projects in the `GetAllRepositoriesFiltered` method. 
Usage:
```go
params := services.NewRepositoriesFilterParams()
params.ProjectKey = "project-key"
err := servicesManager.GetAllRepositoriesFiltered(params)
```
See also https://github.com/jfrog/jfrog-client-go?tab=readme-ov-file#getting-all-repositories.

We would appreciate your feedback on this update.
